-- Application users (login). Each user has exactly one role.
CREATE TABLE app_user (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(150) NOT NULL UNIQUE,
    password_hash varchar(100) NOT NULL,
    full_name     varchar(120) NOT NULL,
    role          varchar(20)  NOT NULL CHECK (role IN ('ADMIN', 'SELLER')),
    active        boolean      NOT NULL DEFAULT true,
    created_at    timestamptz  NOT NULL DEFAULT now()
);

-- Sellers. Optionally linked to the user account they sign in with.
CREATE TABLE seller (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(120) NOT NULL,
    email      varchar(150) NOT NULL UNIQUE,
    phone      varchar(30),
    user_id    integer UNIQUE REFERENCES app_user (id),
    active     boolean      NOT NULL DEFAULT true,
    created_at timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE customer (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(120) NOT NULL,
    email      varchar(150) UNIQUE,
    phone      varchar(30),
    document   varchar(20) UNIQUE,
    created_at timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE product (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               varchar(120)  NOT NULL,
    characteristics    varchar(500),
    brand              varchar(80)   NOT NULL,
    price              numeric(12, 2) NOT NULL CHECK (price >= 0),
    manufacturing_date date,
    created_at         timestamptz   NOT NULL DEFAULT now()
);

-- A sale belongs to one seller and one customer.
CREATE TABLE sale (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id    integer        NOT NULL REFERENCES seller (id),
    customer_id  integer        NOT NULL REFERENCES customer (id),
    sale_date    date           NOT NULL DEFAULT current_date,
    total_amount numeric(14, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    notes        varchar(500),
    created_at   timestamptz    NOT NULL DEFAULT now(),
    updated_at   timestamptz    NOT NULL DEFAULT now()
);

CREATE INDEX idx_sale_seller ON sale (seller_id);
CREATE INDEX idx_sale_customer ON sale (customer_id);

-- N:N between sale and product. Keeps quantity and the unit price at the time of sale,
-- so later product price changes do not alter past sales.
CREATE TABLE sale_item (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id    integer        NOT NULL REFERENCES sale (id) ON DELETE CASCADE,
    product_id integer        NOT NULL REFERENCES product (id),
    quantity   integer        NOT NULL CHECK (quantity > 0),
    unit_price numeric(12, 2) NOT NULL CHECK (unit_price >= 0),
    CONSTRAINT uq_sale_item_product UNIQUE (sale_id, product_id)
);

CREATE INDEX idx_sale_item_product ON sale_item (product_id);
